# Generated by Django 4.1.5 on 2023-07-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
